/* Auto-generated by gen_offsets_header.py - do not hand-edit. */
#ifndef OFFSETS_DATA_H
#define OFFSETS_DATA_H

typedef struct {
    CONST CHAR16 *StoreName;
    UINTN Offset;
    UINTN Size;
    CONST CHAR16 *Desc;
} PREFILLED_ENTRY;

STATIC PREFILLED_ENTRY KNOWN_OFFSETS[] = {
    { L"", 0, 0, L"" },
};
#define KNOWN_OFFSETS_COUNT 0

STATIC PREFILLED_ENTRY CUSTOM_OFFSETS[] = {
    { L"", 0, 0, L"" },
};
#define CUSTOM_OFFSETS_COUNT 0

#endif /* OFFSETS_DATA_H */
