/*
 * SetupVarGUI - native UEFI application, menu-driven GUI front-end for
 * reading/writing "Setup"-style hidden BIOS/UEFI NVRAM variables.
 *
 * Same underlying technique as community CLI tools (setup_var.efi,
 * grub-mod-setup_var, etc.): locate a firmware NVRAM variable by name
 * (e.g. "Setup"), read its raw byte buffer via GetVariable, patch a
 * byte/word/dword at a given offset, and write it back with SetVariable.
 *
 * *** DANGER ***
 * Writing wrong values to firmware Setup variables can permanently brick
 * your motherboard. Only use offsets you have verified (e.g. via IFR
 * extraction) for your EXACT firmware version. You use this at your own
 * risk.
 *
 * Build: see build.sh (uses gnu-efi, no EDK2 required)
 */

#include <efi.h>
#include <efilib.h>
#include "offsets_data.h"  /* generated by pipeline/gen_offsets_header.py;
                              a placeholder with empty arrays ships by
                              default so plain build.sh still works. */

#define APP_TITLE       L"SetupVar GUI"
#define APP_VERSION     L"v1.0"
#define MAX_LINE        256
#define MAX_VARNAME     512
#define MAX_VARLIST     512
#define MAX_CFG_ENTRIES 128

/* ---- colors ---------------------------------------------------------- */
#define COL_HEADER   EFI_TEXT_ATTR(EFI_WHITE, EFI_BLUE)
#define COL_NORMAL   EFI_TEXT_ATTR(EFI_LIGHTGRAY, EFI_BLACK)
#define COL_DIM      EFI_TEXT_ATTR(EFI_DARKGRAY, EFI_BLACK)
#define COL_SEL      EFI_TEXT_ATTR(EFI_BLACK, EFI_CYAN)
#define COL_WARN     EFI_TEXT_ATTR(EFI_YELLOW, EFI_RED)
#define COL_OK       EFI_TEXT_ATTR(EFI_LIGHTGREEN, EFI_BLACK)
#define COL_FOOTER   EFI_TEXT_ATTR(EFI_BLACK, EFI_LIGHTGRAY)

STATIC EFI_GUID gVendorGuid = EFI_GLOBAL_VARIABLE;

typedef struct {
    CHAR16  Name[MAX_VARNAME];
    EFI_GUID Guid;
} VAR_ENTRY;

typedef struct {
    CHAR16  StoreName[64];
    UINTN   Offset;
    UINTN   Size;       /* 1, 2 or 4 */
    UINT32  Value;
    CHAR16  Desc[128];
} CFG_ENTRY;

/* ------------------------------------------------------------------ */
/*  low level helpers                                                 */
/* ------------------------------------------------------------------ */

STATIC VOID ClearScreen(VOID)
{
    uefi_call_wrapper(ST->ConOut->ClearScreen, 1, ST->ConOut);
}

STATIC VOID SetAttr(UINTN attr)
{
    uefi_call_wrapper(ST->ConOut->SetAttribute, 2, ST->ConOut, attr);
}

STATIC VOID GotoXY(UINTN x, UINTN y)
{
    uefi_call_wrapper(ST->ConOut->SetCursorPosition, 3, ST->ConOut, x, y);
}

STATIC VOID HideCursor(VOID)
{
    uefi_call_wrapper(ST->ConOut->EnableCursor, 2, ST->ConOut, FALSE);
}

STATIC VOID ShowCursor(VOID)
{
    uefi_call_wrapper(ST->ConOut->EnableCursor, 2, ST->ConOut, TRUE);
}

STATIC VOID PadLine(UINTN width)
{
    UINTN i;
    for (i = 0; i < width; i++) Print(L" ");
}

STATIC VOID DrawHeader(CONST CHAR16 *subtitle)
{
    ClearScreen();
    SetAttr(COL_HEADER);
    GotoXY(0, 0);
    PadLine(80);
    GotoXY(2, 0);
    Print(L"%s %s  -  %s", APP_TITLE, APP_VERSION, subtitle);
    SetAttr(COL_NORMAL);
    GotoXY(0, 1);
    Print(L"----------------------------------------------------------------------------");
}

STATIC VOID DrawFooter(CONST CHAR16 *hint)
{
    SetAttr(COL_FOOTER);
    GotoXY(0, 24);
    PadLine(80);
    GotoXY(2, 24);
    Print(L"%s", hint);
    SetAttr(COL_NORMAL);
}

STATIC EFI_INPUT_KEY WaitKey(VOID)
{
    EFI_INPUT_KEY Key;
    UINTN Index;
    EFI_STATUS Status;

    do {
        uefi_call_wrapper(BS->WaitForEvent, 3, 1, &ST->ConIn->WaitForKey, &Index);
        Status = uefi_call_wrapper(ST->ConIn->ReadKeyStroke, 2, ST->ConIn, &Key);
    } while (EFI_ERROR(Status));

    return Key;
}

STATIC VOID PressAnyKey(VOID)
{
    DrawFooter(L"Press any key to continue...");
    WaitKey();
}

/* Simple line-editing text/hex input field drawn at (x,y), width chars.
 * If hexOnly, only 0-9 a-f A-f accepted. Returns TRUE if Enter pressed
 * with non-cancelled input, FALSE if user pressed ESC. */
STATIC BOOLEAN InputField(UINTN x, UINTN y, UINTN width, CHAR16 *buf,
                           UINTN bufLen, BOOLEAN hexOnly)
{
    UINTN len = StrLen(buf);
    EFI_INPUT_KEY Key;

    ShowCursor();
    for (;;) {
        GotoXY(x, y);
        SetAttr(COL_SEL);
        PadLine(width);
        GotoXY(x, y);
        Print(L"%s", buf);
        GotoXY(x + len, y);

        Key = WaitKey();

        if (Key.ScanCode == SCAN_ESC) {
            HideCursor();
            SetAttr(COL_NORMAL);
            return FALSE;
        }
        if (Key.UnicodeChar == CHAR_CARRIAGE_RETURN) {
            HideCursor();
            SetAttr(COL_NORMAL);
            return TRUE;
        }
        if (Key.UnicodeChar == CHAR_BACKSPACE) {
            if (len > 0) { len--; buf[len] = 0; }
            continue;
        }
        if (Key.UnicodeChar == 0) continue;

        if (hexOnly) {
            CHAR16 c = Key.UnicodeChar;
            BOOLEAN ok = (c >= L'0' && c <= L'9') ||
                         (c >= L'a' && c <= L'f') ||
                         (c >= L'A' && c <= L'F') ||
                         (c == L'x') || (c == L'X');
            if (!ok) continue;
        }

        if (len + 1 < bufLen && len + 1 < width) {
            buf[len++] = Key.UnicodeChar;
            buf[len] = 0;
        }
    }
}

/* parse a hex string like "0x1A" or "1A" into a UINTN */
STATIC UINTN ParseHex(CONST CHAR16 *s)
{
    UINTN val = 0;
    if (s[0] == L'0' && (s[1] == L'x' || s[1] == L'X')) s += 2;
    while (*s) {
        CHAR16 c = *s++;
        UINTN d;
        if (c >= L'0' && c <= L'9') d = c - L'0';
        else if (c >= L'a' && c <= L'f') d = c - L'a' + 10;
        else if (c >= L'A' && c <= L'F') d = c - L'A' + 10;
        else break;
        val = (val << 4) | d;
    }
    return val;
}

STATIC BOOLEAN Confirm(CONST CHAR16 *msg)
{
    EFI_INPUT_KEY Key;
    SetAttr(COL_WARN);
    GotoXY(2, 20);
    PadLine(76);
    GotoXY(2, 20);
    Print(L"%s [y/N]", msg);
    SetAttr(COL_NORMAL);
    for (;;) {
        Key = WaitKey();
        if (Key.UnicodeChar == L'y' || Key.UnicodeChar == L'Y') return TRUE;
        if (Key.UnicodeChar == L'n' || Key.UnicodeChar == L'N' ||
            Key.ScanCode == SCAN_ESC || Key.UnicodeChar == CHAR_CARRIAGE_RETURN)
            return FALSE;
    }
}

/* ------------------------------------------------------------------ */
/*  NVRAM access                                                      */
/* ------------------------------------------------------------------ */

/* Search all NVRAM variables for one whose name matches wanted.
 * Fills *outGuid. Returns EFI_SUCCESS if found. */
STATIC EFI_STATUS FindVariableGuid(CONST CHAR16 *wanted, EFI_GUID *outGuid)
{
    EFI_STATUS Status;
    UINTN NameSize;
    CHAR16 *VarName;
    EFI_GUID VendorGuid;

    NameSize = MAX_VARNAME * sizeof(CHAR16);
    VarName = AllocateZeroPool(NameSize);
    if (!VarName) return EFI_OUT_OF_RESOURCES;
    VarName[0] = 0;
    ZeroMem(&VendorGuid, sizeof(VendorGuid));

    for (;;) {
        UINTN Size = MAX_VARNAME * sizeof(CHAR16);
        Status = uefi_call_wrapper(RT->GetNextVariableName, 3, &Size, VarName, &VendorGuid);
        if (Status == EFI_NOT_FOUND) break;
        if (Status == EFI_BUFFER_TOO_SMALL) {
            FreePool(VarName);
            VarName = AllocateZeroPool(Size);
            if (!VarName) return EFI_OUT_OF_RESOURCES;
            Status = uefi_call_wrapper(RT->GetNextVariableName, 3, &Size, VarName, &VendorGuid);
        }
        if (EFI_ERROR(Status)) break;

        if (StrCmp(VarName, (CHAR16 *)wanted) == 0) {
            CopyMem(outGuid, &VendorGuid, sizeof(EFI_GUID));
            FreePool(VarName);
            return EFI_SUCCESS;
        }
    }

    FreePool(VarName);
    return EFI_NOT_FOUND;
}

/* Enumerate ALL NVRAM variables into a caller array, returns count. */
STATIC UINTN EnumerateVariables(VAR_ENTRY *arr, UINTN maxCount)
{
    EFI_STATUS Status;
    CHAR16 *VarName;
    EFI_GUID VendorGuid;
    UINTN count = 0;

    VarName = AllocateZeroPool(MAX_VARNAME * sizeof(CHAR16));
    if (!VarName) return 0;
    VarName[0] = 0;
    ZeroMem(&VendorGuid, sizeof(VendorGuid));

    for (;;) {
        UINTN Size = MAX_VARNAME * sizeof(CHAR16);
        Status = uefi_call_wrapper(RT->GetNextVariableName, 3, &Size, VarName, &VendorGuid);
        if (Status == EFI_NOT_FOUND) break;
        if (Status == EFI_BUFFER_TOO_SMALL) {
            FreePool(VarName);
            VarName = AllocateZeroPool(Size);
            if (!VarName) break;
            Status = uefi_call_wrapper(RT->GetNextVariableName, 3, &Size, VarName, &VendorGuid);
        }
        if (EFI_ERROR(Status)) break;

        if (count < maxCount) {
            StrCpy(arr[count].Name, VarName);
            CopyMem(&arr[count].Guid, &VendorGuid, sizeof(EFI_GUID));
            count++;
        } else {
            break;
        }
    }

    FreePool(VarName);
    return count;
}

STATIC EFI_STATUS ReadVarBuffer(CONST CHAR16 *name, EFI_GUID *guid,
                                 VOID **data, UINTN *size, UINT32 *attr)
{
    EFI_STATUS Status;
    UINTN Size = 0;

    Status = uefi_call_wrapper(RT->GetVariable, 5, (CHAR16 *)name, guid, attr, &Size, NULL);
    if (Status != EFI_BUFFER_TOO_SMALL) return Status;

    *data = AllocateZeroPool(Size);
    if (!*data) return EFI_OUT_OF_RESOURCES;

    Status = uefi_call_wrapper(RT->GetVariable, 5, (CHAR16 *)name, guid, attr, &Size, *data);
    if (EFI_ERROR(Status)) { FreePool(*data); *data = NULL; return Status; }

    *size = Size;
    return EFI_SUCCESS;
}

/* ------------------------------------------------------------------ */
/*  screens                                                            */
/* ------------------------------------------------------------------ */

STATIC VOID ScreenAbout(VOID)
{
    DrawHeader(L"About / Disclaimer");
    GotoXY(2, 3);
    Print(L"SetupVar GUI reads and writes raw bytes inside firmware NVRAM");
    GotoXY(2, 4);
    Print(L"\"Setup\"-style variables, the same variables the BIOS setup menu");
    GotoXY(2, 5);
    Print(L"itself edits. This lets you toggle hidden/greyed-out settings.");
    SetAttr(COL_WARN);
    GotoXY(2, 8);
    Print(L" WARNING: wrong offsets/values can permanently brick your board. ");
    GotoXY(2, 9);
    Print(L" Only use offsets you verified for your EXACT firmware version.  ");
    GotoXY(2, 10);
    Print(L" (e.g. via IFR extraction). Use at your own risk.                ");
    SetAttr(COL_NORMAL);
    GotoXY(2, 13);
    Print(L"Underlying operations:");
    GotoXY(2, 14);
    Print(L"  Read  : GetVariable(name, guid) -> raw byte buffer");
    GotoXY(2, 15);
    Print(L"  Write : patch byte/word/dword at offset -> SetVariable(...)");
    PressAnyKey();
}

/* Edit a single value at a known name+guid. If guid is NULL, it will be
 * looked up by name first. If havePrefill is TRUE, the offset/size are
 * taken from prefillOffset/prefillSize (from a Known/Custom offsets list)
 * instead of being typed in, and prefillLabel (if non-NULL) is shown. */
STATIC VOID EditVariableValue2(CONST CHAR16 *storeName, EFI_GUID *knownGuid,
                                BOOLEAN havePrefill, UINTN prefillOffset,
                                UINTN prefillSize, CONST CHAR16 *prefillLabel)
{
    EFI_GUID guid;
    EFI_STATUS Status;
    VOID *data = NULL;
    UINTN size = 0;
    UINT32 attr = 0;
    CHAR16 offBuf[32] = L"";
    CHAR16 sizeBuf[8] = L"1";
    CHAR16 valBuf[16] = L"";
    UINTN offset, valsize;
    UINT32 curVal = 0, newVal;

    DrawHeader(L"Edit Variable");

    if (knownGuid) {
        CopyMem(&guid, knownGuid, sizeof(EFI_GUID));
    } else {
        GotoXY(2, 3);
        Print(L"Locating variable \"%s\" in NVRAM...", storeName);
        Status = FindVariableGuid(storeName, &guid);
        if (EFI_ERROR(Status)) {
            SetAttr(COL_WARN);
            GotoXY(2, 5);
            Print(L"Variable \"%s\" not found in NVRAM.", storeName);
            SetAttr(COL_NORMAL);
            PressAnyKey();
            return;
        }
    }

    Status = ReadVarBuffer(storeName, &guid, &data, &size, &attr);
    if (EFI_ERROR(Status)) {
        SetAttr(COL_WARN);
        GotoXY(2, 5);
        Print(L"Failed to read variable: %r", Status);
        SetAttr(COL_NORMAL);
        PressAnyKey();
        return;
    }

    GotoXY(2, 3);
    Print(L"Variable   : %s", storeName);
    GotoXY(2, 4);
    Print(L"GUID       : %g", &guid);
    GotoXY(2, 5);
    Print(L"Data size  : %d (0x%x) bytes   Attributes: 0x%x", size, size, attr);
    if (prefillLabel && StrLen(prefillLabel) > 0) {
        SetAttr(COL_OK);
        GotoXY(2, 6);
        Print(L"Setting    : %s", prefillLabel);
        SetAttr(COL_NORMAL);
    }

    if (havePrefill) {
        offset = prefillOffset;
        valsize = (prefillSize == 1 || prefillSize == 2 || prefillSize == 4) ? prefillSize : 1;
        GotoXY(2, 8);
        Print(L"Offset (from list): 0x%x   Size: %d byte(s)", offset, valsize);
    } else {
        GotoXY(2, 8);
        Print(L"Offset (hex, e.g. 0x1A): ");
        if (!InputField(30, 8, 20, offBuf, 32, TRUE) || StrLen(offBuf) == 0) {
            FreePool(data);
            return;
        }
        offset = ParseHex(offBuf);

        GotoXY(2, 9);
        Print(L"Value size in bytes (1, 2 or 4): ");
        InputField(38, 9, 4, sizeBuf, 8, TRUE);
        valsize = ParseHex(sizeBuf);
        if (valsize != 1 && valsize != 2 && valsize != 4) valsize = 1;
    }

    if (offset + valsize > size) {
        SetAttr(COL_WARN);
        GotoXY(2, 12);
        Print(L"Offset+size is outside the variable's data (max offset 0x%x).", size - 1);
        SetAttr(COL_NORMAL);
        PressAnyKey();
        FreePool(data);
        return;
    }

    /* read current */
    curVal = 0;
    CopyMem(&curVal, (UINT8 *)data + offset, valsize);

    GotoXY(2, 11);
    Print(L"Current value at offset 0x%x (%d-byte): 0x%x", offset, valsize, curVal);

    GotoXY(2, 14);
    Print(L"New value (hex, leave blank to just read/cancel): ");
    if (!InputField(54, 14, 12, valBuf, 16, TRUE) || StrLen(valBuf) == 0) {
        FreePool(data);
        PressAnyKey();
        return;
    }
    newVal = (UINT32)ParseHex(valBuf);

    GotoXY(2, 16);
    Print(L"About to write 0x%x -> offset 0x%x of \"%s\" (was 0x%x).",
          newVal, offset, storeName, curVal);

    if (Confirm(L"This can brick your firmware if wrong. Really write?")) {
        CopyMem((UINT8 *)data + offset, &newVal, valsize);
        Status = uefi_call_wrapper(RT->SetVariable, 5, (CHAR16 *)storeName, &guid,
                                    attr, size, data);
        GotoXY(2, 22);
        if (EFI_ERROR(Status)) {
            SetAttr(COL_WARN);
            Print(L"SetVariable failed: %r", Status);
        } else {
            SetAttr(COL_OK);
            Print(L"Write OK. New value committed to NVRAM.");
        }
        SetAttr(COL_NORMAL);
    } else {
        GotoXY(2, 22);
        Print(L"Cancelled, no changes written.");
    }

    FreePool(data);
    PressAnyKey();
}

STATIC VOID EditVariableValue(CONST CHAR16 *storeName, EFI_GUID *knownGuid)
{
    EditVariableValue2(storeName, knownGuid, FALSE, 0, 0, NULL);
}

STATIC VOID ScreenEditByName(VOID)
{
    CHAR16 nameBuf[64] = L"Setup";

    DrawHeader(L"Edit Variable by Name");
    GotoXY(2, 3);
    Print(L"Variable store name (default is \"Setup\", some firmwares use");
    GotoXY(2, 4);
    Print(L"\"Custom\", or an OEM-specific name):");
    GotoXY(2, 6);
    Print(L"Name: ");
    if (!InputField(8, 6, 40, nameBuf, 64, FALSE)) return;
    if (StrLen(nameBuf) == 0) StrCpy(nameBuf, L"Setup");

    EditVariableValue(nameBuf, NULL);
}

STATIC VOID ScreenBrowseVariables(VOID)
{
    VAR_ENTRY *vars;
    UINTN count, sel = 0, top = 0, visible = 18;
    EFI_INPUT_KEY Key;

    vars = AllocateZeroPool(sizeof(VAR_ENTRY) * MAX_VARLIST);
    if (!vars) return;

    DrawHeader(L"Browse NVRAM Variables");
    GotoXY(2, 3);
    Print(L"Enumerating NVRAM variables, please wait...");
    count = EnumerateVariables(vars, MAX_VARLIST);

    if (count == 0) {
        SetAttr(COL_WARN);
        GotoXY(2, 5);
        Print(L"No variables enumerated (or access denied).");
        SetAttr(COL_NORMAL);
        PressAnyKey();
        FreePool(vars);
        return;
    }

    for (;;) {
        UINTN i;
        DrawHeader(L"Browse NVRAM Variables");
        GotoXY(2, 2);
        Print(L"%d variables found. Enter = edit, Esc = back.", count);

        for (i = 0; i < visible && (top + i) < count; i++) {
            UINTN idx = top + i;
            GotoXY(2, 4 + i);
            if (idx == sel) SetAttr(COL_SEL); else SetAttr(COL_NORMAL);
            PadLine(76);
            GotoXY(2, 4 + i);
            Print(L"%s", vars[idx].Name);
            SetAttr(COL_NORMAL);
        }

        DrawFooter(L"Up/Down: move   PgUp/PgDn: page   Enter: select   Esc: back");

        Key = WaitKey();
        if (Key.ScanCode == SCAN_UP) {
            if (sel > 0) sel--;
            if (sel < top) top = sel;
        } else if (Key.ScanCode == SCAN_DOWN) {
            if (sel + 1 < count) sel++;
            if (sel >= top + visible) top = sel - visible + 1;
        } else if (Key.ScanCode == SCAN_PAGE_UP) {
            if (sel > visible) sel -= visible; else sel = 0;
            top = sel;
        } else if (Key.ScanCode == SCAN_PAGE_DOWN) {
            if (sel + visible < count) sel += visible; else sel = count - 1;
            if (sel >= top + visible) top = sel - visible + 1;
        } else if (Key.ScanCode == SCAN_ESC) {
            break;
        } else if (Key.UnicodeChar == CHAR_CARRIAGE_RETURN) {
            EditVariableValue(vars[sel].Name, &vars[sel].Guid);
        }
    }

    FreePool(vars);
}

/* Browse a compiled-in list of (store,offset,size,label) entries -
 * baked in at build time from a BIOS scan ("Known Offsets") or a
 * hand-written CSV ("Custom Offsets"). Enter jumps straight into the
 * editor with the offset/size prefilled. */
STATIC VOID ScreenPrefilledList(PREFILLED_ENTRY *entries, UINTN count,
                                 CONST CHAR16 *screenTitle)
{
    UINTN sel = 0, top = 0, visible = 18;
    EFI_INPUT_KEY Key;

    if (count == 0) {
        DrawHeader(screenTitle);
        SetAttr(COL_WARN);
        GotoXY(2, 4);
        Print(L"No entries baked into this binary.");
        SetAttr(COL_NORMAL);
        GotoXY(2, 6);
        Print(L"Run the build_all.sh pipeline against a BIOS image (and/or");
        GotoXY(2, 7);
        Print(L"provide a custom_offsets.csv) to populate this list, then");
        GotoXY(2, 8);
        Print(L"rebuild the binary.");
        PressAnyKey();
        return;
    }

    for (;;) {
        UINTN i;
        DrawHeader(screenTitle);
        GotoXY(2, 2);
        Print(L"%d entries. Enter = edit, Esc = back.", count);

        for (i = 0; i < visible && (top + i) < count; i++) {
            UINTN idx = top + i;
            GotoXY(2, 4 + i);
            if (idx == sel) SetAttr(COL_SEL); else SetAttr(COL_NORMAL);
            PadLine(76);
            GotoXY(2, 4 + i);
            Print(L"%s:0x%x(%d)  %s", entries[idx].StoreName,
                  entries[idx].Offset, entries[idx].Size, entries[idx].Desc);
            SetAttr(COL_NORMAL);
        }

        DrawFooter(L"Up/Down: move   PgUp/PgDn: page   Enter: select   Esc: back");

        Key = WaitKey();
        if (Key.ScanCode == SCAN_UP) {
            if (sel > 0) sel--;
            if (sel < top) top = sel;
        } else if (Key.ScanCode == SCAN_DOWN) {
            if (sel + 1 < count) sel++;
            if (sel >= top + visible) top = sel - visible + 1;
        } else if (Key.ScanCode == SCAN_PAGE_UP) {
            if (sel > visible) sel -= visible; else sel = 0;
            top = sel;
        } else if (Key.ScanCode == SCAN_PAGE_DOWN) {
            if (sel + visible < count) sel += visible; else sel = count - 1;
            if (sel >= top + visible) top = sel - visible + 1;
        } else if (Key.ScanCode == SCAN_ESC) {
            break;
        } else if (Key.UnicodeChar == CHAR_CARRIAGE_RETURN) {
            EditVariableValue2(entries[sel].StoreName, NULL, TRUE,
                                entries[sel].Offset, entries[sel].Size,
                                entries[sel].Desc);
        }
    }
}

STATIC VOID ScreenKnownOffsets(VOID)
{
    ScreenPrefilledList(KNOWN_OFFSETS, KNOWN_OFFSETS_COUNT,
                         L"Known Offsets (from BIOS scan)");
}

STATIC VOID ScreenCustomOffsets(VOID)
{
    ScreenPrefilledList(CUSTOM_OFFSETS, CUSTOM_OFFSETS_COUNT,
                         L"Custom Offsets");
}

/* ---- config file batch mode ---------------------------------------- */

STATIC EFI_FILE_HANDLE OpenAppDirRoot(EFI_HANDLE ImageHandle)
{
    EFI_STATUS Status;
    EFI_LOADED_IMAGE *LoadedImage = NULL;
    EFI_FILE_IO_INTERFACE *FioIface = NULL;
    EFI_FILE_HANDLE Root = NULL;

    Status = uefi_call_wrapper(BS->HandleProtocol, 3, ImageHandle,
                                &LoadedImageProtocol, (VOID **)&LoadedImage);
    if (EFI_ERROR(Status) || !LoadedImage) return NULL;

    Status = uefi_call_wrapper(BS->HandleProtocol, 3, LoadedImage->DeviceHandle,
                                &FileSystemProtocol, (VOID **)&FioIface);
    if (EFI_ERROR(Status) || !FioIface) return NULL;

    Status = uefi_call_wrapper(FioIface->OpenVolume, 2, FioIface, &Root);
    if (EFI_ERROR(Status)) return NULL;

    return Root;
}

/* very small line-based parser:
 *   StoreName:0xOFFSET(SIZE)=0xVALUE ; free text description
 * blank lines and lines starting with ';' or '#' are ignored.       */
STATIC UINTN ParseConfigText(CHAR8 *text, UINTN textLen, CFG_ENTRY *out, UINTN maxOut)
{
    UINTN pos = 0, count = 0;

    while (pos < textLen && count < maxOut) {
        CHAR8 line[MAX_LINE];
        UINTN li = 0;

        while (pos < textLen && text[pos] != '\n' && li < MAX_LINE - 1) {
            if (text[pos] != '\r') line[li++] = text[pos];
            pos++;
        }
        while (pos < textLen && text[pos] != '\n') pos++;
        if (pos < textLen) pos++; /* skip \n */
        line[li] = 0;

        if (li == 0 || line[0] == ';' || line[0] == '#') continue;

        /* find colon */
        UINTN i = 0, j;
        CHAR16 store[64];
        UINTN si = 0;
        while (line[i] && line[i] != ':' && si < 63) store[si++] = (CHAR16)line[i++];
        store[si] = 0;
        if (line[i] != ':') continue;
        i++;

        if (line[i] != '0' || (line[i+1] != 'x' && line[i+1] != 'X')) continue;
        i += 2;
        UINTN off = 0;
        while ((line[i] >= '0' && line[i] <= '9') ||
               (line[i] >= 'a' && line[i] <= 'f') ||
               (line[i] >= 'A' && line[i] <= 'F')) {
            CHAR8 c = line[i];
            UINTN d = (c >= '0' && c <= '9') ? c - '0' :
                      (c >= 'a' && c <= 'f') ? c - 'a' + 10 : c - 'A' + 10;
            off = (off << 4) | d;
            i++;
        }

        UINTN sz = 1;
        if (line[i] == '(') {
            i++;
            sz = 0;
            while (line[i] >= '0' && line[i] <= '9') { sz = sz * 10 + (line[i] - '0'); i++; }
            if (line[i] == ')') i++;
        }

        if (line[i] != '=') continue;
        i++;
        if (line[i] != '0' || (line[i+1] != 'x' && line[i+1] != 'X')) continue;
        i += 2;
        UINT32 val = 0;
        while ((line[i] >= '0' && line[i] <= '9') ||
               (line[i] >= 'a' && line[i] <= 'f') ||
               (line[i] >= 'A' && line[i] <= 'F')) {
            CHAR8 c = line[i];
            UINTN d = (c >= '0' && c <= '9') ? c - '0' :
                      (c >= 'a' && c <= 'f') ? c - 'a' + 10 : c - 'A' + 10;
            val = (val << 4) | (UINT32)d;
            i++;
        }

        /* optional description after ';' */
        CHAR16 desc[128];
        UINTN di = 0;
        desc[0] = 0;
        while (line[i] && line[i] != ';') i++;
        if (line[i] == ';') {
            i++;
            while (line[i] == ' ') i++;
            while (line[i] && di < 127) desc[di++] = (CHAR16)line[i++];
        }
        desc[di] = 0;

        for (j = 0; j < si; j++) out[count].StoreName[j] = store[j];
        out[count].StoreName[si] = 0;
        out[count].Offset = off;
        out[count].Size = (sz == 2 || sz == 4) ? sz : 1;
        out[count].Value = val;
        StrCpy(out[count].Desc, desc);
        count++;
    }

    return count;
}

STATIC VOID ScreenLoadConfig(EFI_HANDLE ImageHandle)
{
    EFI_FILE_HANDLE Root, File;
    EFI_STATUS Status;
    CFG_ENTRY *entries;
    UINTN count = 0;
    BOOLEAN *selected;
    CHAR8 *buf;
    UINTN bufSize;
    EFI_FILE_INFO *info;
    UINTN infoSize;

    DrawHeader(L"Load Config File (batch)");
    GotoXY(2, 3);
    Print(L"Looking for \\setupvar.cfg next to this .efi file...");

    Root = OpenAppDirRoot(ImageHandle);
    if (!Root) {
        SetAttr(COL_WARN);
        GotoXY(2, 5);
        Print(L"Could not open filesystem root.");
        SetAttr(COL_NORMAL);
        PressAnyKey();
        return;
    }

    Status = uefi_call_wrapper(Root->Open, 5, Root, &File, L"setupvar.cfg",
                                EFI_FILE_MODE_READ, 0);
    if (EFI_ERROR(Status)) {
        SetAttr(COL_WARN);
        GotoXY(2, 5);
        Print(L"setupvar.cfg not found in the same directory as this app.");
        GotoXY(2, 6);
        SetAttr(COL_NORMAL);
        Print(L"Format, one entry per line:");
        GotoXY(2, 7);
        Print(L"  Setup:0x0CA9(1)=0x01 ; Intel C-State");
        PressAnyKey();
        return;
    }

    infoSize = SIZE_OF_EFI_FILE_INFO + 256;
    info = AllocateZeroPool(infoSize);
    uefi_call_wrapper(File->GetInfo, 4, File, &GenericFileInfo, &infoSize, info);
    bufSize = (UINTN)info->FileSize;
    FreePool(info);

    buf = AllocateZeroPool(bufSize + 1);
    uefi_call_wrapper(File->Read, 3, File, &bufSize, buf);
    uefi_call_wrapper(File->Close, 1, File);

    entries = AllocateZeroPool(sizeof(CFG_ENTRY) * MAX_CFG_ENTRIES);
    selected = AllocateZeroPool(sizeof(BOOLEAN) * MAX_CFG_ENTRIES);
    count = ParseConfigText(buf, bufSize, entries, MAX_CFG_ENTRIES);
    FreePool(buf);

    if (count == 0) {
        SetAttr(COL_WARN);
        GotoXY(2, 5);
        Print(L"No valid entries parsed from setupvar.cfg.");
        SetAttr(COL_NORMAL);
        PressAnyKey();
        FreePool(entries);
        FreePool(selected);
        return;
    }

    UINTN sel = 0;
    EFI_INPUT_KEY Key;
    for (;;) {
        UINTN i;
        DrawHeader(L"Load Config File (batch)");
        GotoXY(2, 2);
        Print(L"%d entries. Space = toggle, A = apply checked, Esc = back.", count);

        for (i = 0; i < count && i < 16; i++) {
            GotoXY(2, 4 + i);
            if (i == sel) SetAttr(COL_SEL); else SetAttr(COL_NORMAL);
            PadLine(76);
            GotoXY(2, 4 + i);
            Print(L"[%c] %s:0x%x(%d)=0x%x  %s",
                  selected[i] ? L'x' : L' ',
                  entries[i].StoreName, entries[i].Offset, entries[i].Size,
                  entries[i].Value, entries[i].Desc);
            SetAttr(COL_NORMAL);
        }

        DrawFooter(L"Up/Down: move   Space: toggle   A: apply selected   Esc: back");

        Key = WaitKey();
        if (Key.ScanCode == SCAN_UP) { if (sel > 0) sel--; }
        else if (Key.ScanCode == SCAN_DOWN) { if (sel + 1 < count) sel++; }
        else if (Key.ScanCode == SCAN_ESC) break;
        else if (Key.UnicodeChar == L' ') selected[sel] = !selected[sel];
        else if (Key.UnicodeChar == L'a' || Key.UnicodeChar == L'A') {
            UINTN n;
            BOOLEAN any = FALSE;
            for (n = 0; n < count; n++) if (selected[n]) any = TRUE;
            if (!any) continue;
            if (!Confirm(L"Apply all checked entries? This writes NVRAM now.")) continue;

            for (n = 0; n < count; n++) {
                if (!selected[n]) continue;
                EFI_GUID guid;
                VOID *data = NULL;
                UINTN dsize = 0;
                UINT32 attr = 0;

                if (EFI_ERROR(FindVariableGuid(entries[n].StoreName, &guid))) continue;
                if (EFI_ERROR(ReadVarBuffer(entries[n].StoreName, &guid, &data, &dsize, &attr))) continue;
                if (entries[n].Offset + entries[n].Size <= dsize) {
                    CopyMem((UINT8 *)data + entries[n].Offset, &entries[n].Value, entries[n].Size);
                    uefi_call_wrapper(RT->SetVariable, 5, entries[n].StoreName, &guid,
                                       attr, dsize, data);
                }
                FreePool(data);
            }
            GotoXY(2, 22);
            SetAttr(COL_OK);
            Print(L"Batch apply finished.");
            SetAttr(COL_NORMAL);
            PressAnyKey();
        }
    }

    FreePool(entries);
    FreePool(selected);
}

/* ------------------------------------------------------------------ */
/*  main menu                                                          */
/* ------------------------------------------------------------------ */

STATIC CONST CHAR16 *MainMenuItems[] = {
    L"Edit variable by name / offset",
    L"Browse all NVRAM variables",
    L"Known offsets (from BIOS scan)",
    L"Custom offsets",
    L"Load & apply config file (batch)",
    L"About / disclaimer",
    L"Exit",
};
#define MAIN_MENU_COUNT 7

EFI_STATUS EFIAPI efi_main(EFI_HANDLE ImageHandle, EFI_SYSTEM_TABLE *SystemTable)
{
    UINTN sel = 0;
    EFI_INPUT_KEY Key;
    BOOLEAN acceptedWarning = FALSE;

    InitializeLib(ImageHandle, SystemTable);
    uefi_call_wrapper(ST->ConOut->SetMode, 2, ST->ConOut, 0);
    HideCursor();

    /* splash / disclaimer gate */
    DrawHeader(L"Welcome");
    SetAttr(COL_WARN);
    GotoXY(2, 4);
    Print(L" This tool edits raw firmware NVRAM variables (hidden BIOS      ");
    GotoXY(2, 5);
    Print(L" settings). Incorrect use CAN PERMANENTLY BRICK your device.    ");
    SetAttr(COL_NORMAL);
    GotoXY(2, 8);
    Print(L"Proceed only if you understand the risk and know what you are doing.");
    if (!Confirm(L"Continue?")) {
        return EFI_SUCCESS;
    }
    acceptedWarning = TRUE;
    (VOID)acceptedWarning;

    for (;;) {
        UINTN i;
        DrawHeader(L"Main Menu");

        for (i = 0; i < MAIN_MENU_COUNT; i++) {
            GotoXY(4, 4 + i * 2);
            if (i == sel) SetAttr(COL_SEL); else SetAttr(COL_NORMAL);
            PadLine(50);
            GotoXY(4, 4 + i * 2);
            Print(L" %d. %s", i + 1, MainMenuItems[i]);
            SetAttr(COL_NORMAL);
        }

        DrawFooter(L"Up/Down: move   Enter: select   Esc: exit");

        Key = WaitKey();
        if (Key.ScanCode == SCAN_UP) {
            sel = (sel == 0) ? MAIN_MENU_COUNT - 1 : sel - 1;
        } else if (Key.ScanCode == SCAN_DOWN) {
            sel = (sel + 1) % MAIN_MENU_COUNT;
        } else if (Key.ScanCode == SCAN_ESC) {
            break;
        } else if (Key.UnicodeChar == CHAR_CARRIAGE_RETURN) {
            switch (sel) {
                case 0: ScreenEditByName(); break;
                case 1: ScreenBrowseVariables(); break;
                case 2: ScreenKnownOffsets(); break;
                case 3: ScreenCustomOffsets(); break;
                case 4: ScreenLoadConfig(ImageHandle); break;
                case 5: ScreenAbout(); break;
                case 6: return EFI_SUCCESS;
            }
        } else if (Key.UnicodeChar >= L'1' && Key.UnicodeChar <= L'7') {
            sel = Key.UnicodeChar - L'1';
            switch (sel) {
                case 0: ScreenEditByName(); break;
                case 1: ScreenBrowseVariables(); break;
                case 2: ScreenKnownOffsets(); break;
                case 3: ScreenCustomOffsets(); break;
                case 4: ScreenLoadConfig(ImageHandle); break;
                case 5: ScreenAbout(); break;
                case 6: return EFI_SUCCESS;
            }
        }
    }

    ClearScreen();
    return EFI_SUCCESS;
}
