#!/usr/bin/env python3
"""
gen_offsets_header.py - turn one or two CSV files (auto-extracted offsets
from a BIOS scan, and/or a hand-written custom offsets list) into a C
header (offsets_data.h) that setupvargui.c #includes, giving the GUI two
built-in menus: "Known Offsets (from BIOS scan)" and "Custom Offsets".

CSV columns expected: store,offset,size,label[,source]
  - store  : NVRAM variable name, e.g. "Setup"          (required)
  - offset : hex like 0x46 or plain decimal              (required)
  - size   : 1, 2 or 4                                    (optional, default 1)
  - label  : free text shown in the menu                  (required)
  - source : ignored by the generator, informational only

Custom CSV (user-authored) may omit columns from the right, e.g. just:
    0x495,above 4g decode
in which case store defaults to "Setup" and size defaults to 1.
"""

import argparse
import csv
import os
import sys

MAX_STORE = 63     # matches CHAR16 StoreName[64] room in the C struct
MAX_LABEL = 127     # matches CHAR16 Desc[128]


def esc_c16(s, maxlen):
    """Escape a python string into the body of a CHAR16 L"..." literal."""
    s = s[:maxlen]
    out = []
    for ch in s:
        cp = ord(ch)
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= cp < 0x7F:
            out.append(ch)
        else:
            out.append('?')  # our text console is ASCII-only
    return ''.join(out)


def parse_int(s):
    s = s.strip()
    if not s:
        return 0
    try:
        return int(s, 16) if s.lower().startswith("0x") else int(s, 10)
    except ValueError:
        return 0


def load_csv(path, default_store="Setup"):
    rows = []
    if not path or not os.path.isfile(path):
        return rows
    with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.reader(f)
        first_real_row = True
        for row in reader:
            if not row or (row[0].strip().startswith("#")):
                continue
            if first_real_row:
                first_real_row = False
                joined = ",".join(row).lower()
                if "offset" in joined and "label" in joined:
                    continue  # header row
            row = [c.strip() for c in row]
            # Flexible column count:
            #  2 cols: offset,label
            #  3 cols: offset,label,store   OR store,offset,label (detect by hex)
            #  4-5 cols (generator's own format): store,offset,size,label[,source]
            if len(row) >= 4 and (row[1].lower().startswith("0x") or row[1].isdigit()):
                store, offset, size, label = row[0], row[1], row[2], row[3]
            elif len(row) == 3:
                # ambiguous: try store,offset,label first
                if row[1].lower().startswith("0x") or row[1].isdigit():
                    store, offset, size, label = row[0], row[1], "1", row[2]
                else:
                    offset, label, store = row[0], row[1], row[2]
                    size = "1"
            elif len(row) == 2:
                offset, label = row[0], row[1]
                store, size = default_store, "1"
            else:
                continue

            off = parse_int(offset)
            sz = parse_int(size) or 1
            if sz not in (1, 2, 4):
                sz = 1
            if not label:
                continue
            rows.append((store or default_store, off, sz, label))
    return rows


def emit_array(rows, c_name):
    lines = []
    lines.append("STATIC PREFILLED_ENTRY %s[] = {" % c_name)
    if not rows:
        lines.append('    { L"", 0, 0, L"" },')
    else:
        for store, off, sz, label in rows:
            store_lit = esc_c16(store, MAX_STORE)
            label_lit = esc_c16(label, MAX_LABEL)
            lines.append('    { L"%s", 0x%X, %d, L"%s" },' %
                          (store_lit, off, sz, label_lit))
    lines.append("};")
    lines.append("#define %s_COUNT %d" % (c_name, len(rows)))
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--known", help="CSV of auto-extracted offsets (from parse_ifr.py)")
    ap.add_argument("--custom", help="CSV of hand-written custom offsets")
    ap.add_argument("-o", "--output", default="offsets_data.h")
    args = ap.parse_args()

    known_rows = load_csv(args.known)
    custom_rows = load_csv(args.custom)

    header = []
    header.append("/* Auto-generated by gen_offsets_header.py - do not hand-edit. */")
    header.append("#ifndef OFFSETS_DATA_H")
    header.append("#define OFFSETS_DATA_H")
    header.append("")
    header.append("typedef struct {")
    header.append("    CONST CHAR16 *StoreName;")
    header.append("    UINTN Offset;")
    header.append("    UINTN Size;")
    header.append("    CONST CHAR16 *Desc;")
    header.append("} PREFILLED_ENTRY;")
    header.append("")
    header.append(emit_array(known_rows, "KNOWN_OFFSETS"))
    header.append("")
    header.append(emit_array(custom_rows, "CUSTOM_OFFSETS"))
    header.append("")
    header.append("#endif /* OFFSETS_DATA_H */")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(header) + "\n")

    print("Wrote %d known + %d custom entries -> %s" %
          (len(known_rows), len(custom_rows), args.output), file=sys.stderr)


if __name__ == "__main__":
    main()
